---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
#    - /bin/cp js $DEPLOYPATH
#    - /bin/cp scss $DEPLOYPATH
#    - /bin/cp img $DEPLOYPATH
#    - /bin/cp fonts $DEPLOYPATH
#    - /bin/cp css $DEPLOYPATH
#    - /bin/cp css $DEPLOYPATH